---
- name: Install Clickhouse
  hosts: clickhouse
  handlers:
    - name: Start clickhouse service
      ansible.builtin.systemd:
        name: clickhouse-server
        state: started
        enabled: true
      become: true
      become_user: root
  tasks:
    - name: Install clickhouse amd64 packages from internet
      become: true
      become_user: root
      ansible.builtin.apt:
        deb: "https://packages.clickhouse.com/deb/pool/main/c/clickhouse-common-static/clickhouse-common-static_{{ clickhouse_version }}_amd64.deb"
      with_items: "{{ clickhouse_amd64_packages }}"
      notify: Start clickhouse service

    - name: Install clickhouse noarch packages from internet
      become: true
      become_user: root
      ansible.builtin.apt:
        deb: "https://packages.clickhouse.com/deb/pool/main/c/{{ item }}/{{ item }}_{{ clickhouse_version }}_all.deb"
      with_items: "{{ clickhouse_noarch_packages }}"
      notify: Start clickhouse service

    - name: Flush handlers
      ansible.builtin.meta: flush_handlers

    - name: Check if database exists
      ansible.builtin.command: "clickhouse-client -q 'SHOW DATABASES;'"
      register: database_exists
      changed_when: false

    - name: Create database
      ansible.builtin.command: "clickhouse-client -q 'create database if not exists logs;'"
      when: database_exists.stdout.find('logs') == -1

    - name: Check if table exists
      ansible.builtin.command: "clickhouse-client -q 'SHOW TABLES FROM logs;'"
      register: table_exists
      changed_when: false

    - name: Create table
      ansible.builtin.command: "clickhouse-client -q '
        CREATE TABLE IF NOT EXISTS logs.logs (
            apname String,
            facility String,
            hostname String,
            message String,
            msgid String,
            procid Int,
            severity String,
            timestamp String,
            version Int
        ) ENGINE = MergeTree ORDER BY timestamp;'"
      when: table_exists.stdout.find('logs') == -1

- name: Install Vector
  hosts: clickhouse
  handlers:
    - name: Restart vector service
      ansible.builtin.systemd:
        name: vector
        state: restarted
        enabled: true
      become: true
      become_user: root
  tasks:
    - name: Install vector packages from internet
      become: true
      become_user: root
      ansible.builtin.apt:
        deb: "https://packages.timber.io/vector/{{ vector_version }}/vector_{{ vector_version }}-1_amd64.deb"
      notify: Restart vector service

    - name: Template a config to /etc/vector/vector.toml
      become: true
      become_user: root
      ansible.builtin.template:
        src: templates/vector.toml
        dest: /etc/vector/vector.toml
        owner: root
        group: root
        mode: "0644"
      notify:
        - Restart vector service
